update bootstrap

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -93,9 +93,9 @@ alias reload="source ~/.zshrc"
 alias editrc="code ~/.zshrc"
 
 # misc
+export EDITOR="vim"
 alias tree="tree -F -I node_modules"
 alias f="open ."
-export EDITOR="vim"
 alias la="ls -la"
 alias lt="ls -lt"
 
@@ -110,27 +110,25 @@ function restart_wifi() {
 export PATH="/usr/local/lib/node_modules:$PATH"
 alias npm-list="npm list -g --depth 0"
 alias yui="yarn upgrade-interactive"
+alias yuil="yarn upgrade-interactive --latest"
 alias np-precheck="f=\$(npm pack);tar -tf \$f; rm \$f"
 npm-bootstrap() {
-  name=$(basename $PWD)
-  user=$(git config github.user)
-
-  git init
-
-  yarn init -y
-  npe description $name
-  npe keywords $name
-  npe repository.type git
-  npe repository.url https://github.com/$user/$name.git
-  npe homepage https://github.com/$user/$name
-  npe bugs.url https://github.com/$user/$name/issues
-  npe scripts.test "echo \"Error: no test specified\" && exit 1"
-  npe scripts.start "node ."
+  local name=$(basename $PWD)
+  local user=$(git config github.user)
+  [ ! -d .git ] && git init
+  [ ! -f package.json ] && yarn init -y
+  [ "$(npe description)" = "undefined" ] && npe description $name
+  [ "$(npe keywords)" = "undefined" ] && npe keywords $name
+  [ "$(npe repository.type)" = "undefined" ] && npe repository.type git
+  [ "$(npe repository.url)" = "undefined" ] && npe repository.url https://github.com/$user/$name.git
+  [ "$(npe homepage)" = "undefined" ] && npe homepage https://github.com/$user/$name
+  [ "$(npe bugs.url)" = "undefined" ] && npe bugs.url https://github.com/$user/$name/issues
+  [ "$(npe scripts.test)" = "undefined" ] && npe scripts.test "echo \"Error: no test specified\" && exit 1"
+  [ "$(npe scripts.start)" = "undefined" ] && npe scripts.start "node index.js"
   fixpack
-
-  gitignore add node
+  [ ! -f .gitignore ] && gitignore add node
   license
-  readme
+  [ ! -f README.md ] && mkreadme
 }
 
 # Python
@@ -181,25 +179,35 @@ alias dea="direnv allow"
 # Git
 export GH="https://github.com"
 alias git="hub"
-alias gt="gittower ."
 alias st="git status"
 alias gd="git diff"
+alias gb="git branch -avv"
 alias recent="git recent"
 alias pull="git pull --rebase"
 alias push="git push -u origin master"
-alias set-upstream="git branch --set-upstream-to=origin/master master"
-alias stashall="git stash -u"
+alias stash-all="git stash -u"
 alias unstash="git stash pop"
+alias gt="gittower ."
 alias lg="lazygit"
+alias delete-merged-branch='git branch --merged|egrep -v ''\*|master''|xargs git branch -d'
+alias set-upstream="git branch -u"
+alias set-upstream-origin-master="git branch --set-upstream-to=origin/master master"
+git-update-upstream() {
+  git fetch upstream
+  git rebase upstream/master
+}
+git-checkout-upstream() {
+  git checkout -b upstream upstream/master
+}
 add() {
   git add $1
   git status
 }
 gu() {
-  gtPrivateKeyPath=$(git config remote.origin.gtPrivateKeyPath)
-  privateKeyPath=${gtPrivateKeyPath:-~/.ssh/id_rsa}
-  gitUser=$(git config user.name)
-  gitEmail=$(git config user.email)
+  local gtPrivateKeyPath=$(git config remote.origin.gtPrivateKeyPath)
+  local privateKeyPath=${gtPrivateKeyPath:-~/.ssh/id_rsa}
+  local gitUser=$(git config user.name)
+  local gitEmail=$(git config user.email)
   echo "Name: ${gitUser}"
   echo "Mail: ${gitEmail}"
   echo "Private: ${privateKeyPath}"
@@ -235,8 +243,15 @@ mdfind-dir() {
 # ghq
 alias get="ghq get"
 
-# mdcat
-alias mat=mdcat
+# gst
+letswork() {
+  local selectedDir=$(gst --short | peco)
+  cd $selectedDir && clear
+}
+
+# Markdown
+alias mat="mdcat -l"
+alias readme="bat -p README*"
 
 # du
 alias volumestat="du -m -x -d 3 ~/Repos/src | awk '\$1 >= 500{print}'"
@@ -273,15 +288,15 @@ dive() {
 # license
 # alias license="yo license --license MIT --name $(git config user.name) --email $(git config user.email) --website"
 license() {
-  license_name=${@:-mit}
-  endpoint="https://raw.githubusercontent.com/licenses/license-templates/master/templates/${license_name}.txt"
+  local license_name=${@:-mit}
+  local endpoint="https://raw.githubusercontent.com/licenses/license-templates/master/templates/${license_name}.txt"
 
-  year=$(date +%Y)
-  username=$(git config user.name)
-  email=$(git config user.email)
-  organization="${username} <${email}>"
+  local year=$(date +%Y)
+  local username=$(git config user.name)
+  local email=$(git config user.email)
+  local organization="${username} <${email}>"
 
-  license_body=$(curl -s ${endpoint})
+  local license_body=$(curl -s ${endpoint})
   if [ $? != 0 ] || [ $license_body = "404: Not Found" ]; then
     echo "No such license: ${@}"
     return
@@ -293,7 +308,7 @@ license() {
 }
 
 # readme
-alias readme="yo standard-readme"
+alias mkreadme="yo standard-readme"
 
 # iTerm2
 source "${HOME}/.iterm2_shell_integration.zsh"
@@ -332,6 +347,8 @@ alias juno="open -a Juno"
 alias d="docker"
 alias da="docker ps -a"
 alias di="docker images"
+alias di="docker images --filter \"{{.Image}}\""
+alias dim="docker images --format \"{{.Repository}}:{{.Tag}}\" | sort"
 alias dip="docker inspect \$(docker ps -lq) | grep IPAddress | cut -d '\"' -f 4"
 alias drm="docker ps -aqf status=exited | xargs docker rm -v"
 alias drmi="docker images -qf dangling=true | xargs docker rmi"
@@ -398,3 +415,7 @@ clearQLCache() {
 }
 
 #zprof
+
+# tabtab source for electron-forge package
+# uninstall by removing these lines or running `tabtab uninstall electron-forge`
+[[ -f /Users/uetchy/Repos/src/github.com/uetchy/nature-remo-macos/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /Users/uetchy/Repos/src/github.com/uetchy/nature-remo-macos/node_modules/tabtab/.completions/electron-forge.zsh
